[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 460800

# Ensure firmware build includes `src` sources (explicit include)
build_src_filter = +<*>
test_build_src = true

build_flags =
; secrets are generated at build-time into include/secrets.h
; build flags for WIFI_SSID/PASSWORD are removed in favor of generated header
extra_scripts = build/generate_secrets.py

lib_deps =
  https://github.com/me-no-dev/AsyncTCP.git
  https://github.com/me-no-dev/ESPAsyncWebServer.git
  bblanchon/ArduinoJson@^7.4.2

lib_ignore =
  WebServer
  ESP32WebServer
